### PR TITLE
Rename "Password slots" to "Direct access slots"

### PR DESCRIPTION
**Pull request by tuxlifan**

### CODE REVIEW

**Comment by nthdimtech** [comment]
I'm not very attached to the current name of the feature and I like the term "direct" but I think it's problematic for discovery that the word "password" isn't in the name. What about "Direct access passwords"? I've thought of various other names before too like "Login screen passwords", etc. How about an informal poll on the mailing list?

**Comment by dumblob** [comment]
As I'm not on the mailing list, here are my quick proposals.

a) `Direct secret kick out`
b) `Login screen secrets`
c) `Direct credential access` (it doesn't have to be used just for passwords :wink:)

**Comment by nthdimtech** [comment]
Good point about passwords. Here is my feedback

a) "Kick out" seems vague
b) Sounds like a chapter title of some kind of "Tips and tricks" book
c) This one I like the most.  I'm worried that the meaning of the word direct could be confused as something to do with the menu action itself. What about "Direct access credentials"

**Comment by nthdimtech** [comment]
Thought about this some more and I think that no wording by itself is going to make it clear what the feature is but I think using the word "direct" is good starting point. So I'm going to call the whole feature "direct mode" and I've renamed the menu item "Direct mode settings" and I've also changed references to "password" to "secret" to make it suitably generic. Take a look at the commit 04d3c33. Let me know how well you think this works

**Comment by tuxlifan** [comment]
'Direct mode' and 'secrets' sounds good to me!
With 'passwords' I feel an obligation to strongly encourage a certain minimum of security but what anybody does with their ✌️secrets✌️ is up to them.

I'll only be able to test 04d3c33 on Tuesday I'm afraid but from a quick look over the diff it looks good.

**Comment by nthdimtech** [comment]
I'm closing this PR then. It can always be tweaked more later.

**Pull request closed without merging**
