### PR TITLE
Development: moc and gitversion

### PR DESCRIPTION
**Pull request by tuxlifan**
1. .gitinore moc_* files
2. Allow addition of a git version string in the About dialog
   (c.f. commit message for f41c6e2)

### CODE REVIEW

**Comment by nthdimtech** [comment]
I like the idea of including the git version but I don't think it should be for developers only or for only one platform. A user might build from git as a way of getting a bug fix before a release is made and I could see this feature being useful to ask them which git revision they were running. It could eliminate the ambiguity between the last time source was pulled vs the last time source was built and deployed.

I think there could be an approach similar to this that would
1) Work on MacOS, MSys2 on Windows, and GNU/Linux
2) Pick up the git version automatically if inside a repository, no steps such as moving a file
3) Not depend on the build being done from the source root. I usually run qmake from a separate folder and if I'm reading this right this code would not work in that case.

**Comment by tuxlifan** [comment]
Running some code to obtain a git version for _all_ builds would certainly make things easier as we wouldn't need to perform the "dance" with .pri file, etc.

ad 1.)
The only reason for currently limiting it to GNU/Linux and developers was the reasoning that developers tend to have git readily installed and that I currently have no sufficient experience with availability/usage details of git/bash on other platforms nor how to implement this in C++ in a good way as an alternative.

Maybe add libgit2 dependency and use [git_describe_format](https://libgit2.github.com/libgit2/#HEAD/group/describe/git_describe_format)?

ad 3.)
The debug_gitversion.sh script would indeed currently only work when called from a direct sub folder of the source root folder or the source root folder itself.
I'm curious: do you create a build/ folder? Inside or outside the source tree?
Using `git rev-parse --show-toplevel` it would be relatively easy to make the script work from any sub directory.
This would however not resolve the issue of git and/or bash not necessarily being available on other platforms in an easy manner.

**Comment by nthdimtech** [comment]
> The only reason for currently limiting it to GNU/Linux and developers was the reasoning that developers tend to have git readily installed and that I currently have no sufficient experience with availability/usage details of git/bash on other platforms nor how to implement this in C++ in a good way as an alternative.

I think it should be supported on three platforms when building as described here: http://nthdimtech.com/signet/downloads/. All three environments have a shell and a way to install git and any other commonly used command line tools. On MacOS you can get what you need through Brew. On MSYS2, through pacman.

> I'm curious: do you create a build/ folder? Inside or outside the source tree?

I create a build folder in the source tree. I think it's reasonable to limit the GIT version checking to in-tree builds.

**Comment by tuxlifan** [comment]
Please test how it works for you with these changes, especially the redirection of stderr to the NUL file on Windows (to not spill the git error message on the screen in case it's not a git repository).

Currently the gitversion.sh script is called twice during 'make' which I believe is a side-effect of touching client/about.cpp after running it to force recompilation and after a git pull one should either re-run qmake or run make twice to make sure the git version is updated.
I think this is not be a big problem since end-users will always need to run qmake first after cloning/downloading and in that case the version is updated correctly.

Another side-effect to note is that running make will always recompile client/about.cpp and relink since we touch it in the gitver target after the gitversion.sh script is run, i.e. there won't be a "Nothing to be done" message from make. If that would be a problem we'd have to check in gitversion.sh if the git version actually changed and only then touch about.cpp from there instead of from the gitver target. I feel that that's not necessary for the moment, though.

**Comment by nthdimtech** [comment]
This is much closer to a solution. The qmake/make quirks you mention worry me though. Is there a way to do this by generating a header file like "config.h" or "version.h". I haven't looked into doing this kind of thing in qmake but I'm guessing it might be more robust.

**Comment by tuxlifan** [comment]
I'll look into that on the weekend.

**Comment by tuxlifan** [comment]
Couldn't stop thinking about it :)
I think now it's as simple as it can get.
An important change was to make gitver a dependency for the `about.o` target instead of the `signet` target so updates of "git describe" are pulled in with the first "make" already.
I added also --dirty for git describe to show if local modifications were made.

**Comment by nthdimtech** [comment]
Yes I know how build system tweaking can get addictive.

Are you sure those system() calls in the pro file are necessary? It would seem to me that the new approach would not require them.

I will probably approve this once I give it another once over. This has gone through so many twists and turns that I think it would be nice to squash all or most of the commits except for the one about ignoring "moc" files. It will be easier for me to give it a final review as a single commit.

**Comment by tuxlifan** [comment]
> Are you sure those system() calls in the pro file are necessary?

Without touching client/gitversion.h first I get 
> client/about.h:4:10: fatal error: gitversion.h: No such file or directory

The system() call to giversion.sh can indeed be removed.

> it would be nice to squash all or most

I hadn't done that yet to preserve the context for previous comments. Happy to be able clean it up, though :)

**Comment by nthdimtech** [comment]
Looks good. Thanks for working this out

**Comment by tuxlifan** [comment]
No problem :) It was absolutely worth it to not be confusing myself anymore which version I'm actually testing... and thank you for your cooperation

**Pull request merged**
